### ISSUE TITLE
support lombok

### ISSUE THREAD

**Issue by abccbaandy** [robohorse/RoboPOJOGenerator#101]
as title

since IDEA bundle lombok, maybe it's popular enough to support.

**Comment by Redick01** [comment]
What version is supported？Do you have a plan？

**Comment by avikghosh** [comment]
Hi @robohorse any plans on supporting Lombok?

**Comment by robohorse** [comment]
Hi guys! Thanks for this issue. I added support for Lombok as experimental feature in the build 2.3.0. I will try to combine it with supported POJO frameworks in the future but I need a little bit more time for it.
