### ISSUE TITLE
Useless modifier: data

### ISSUE THREAD

**Issue by Miha-x64** [robohorse/RoboPOJOGenerator#115]
https://github.com/robohorse/RoboPOJOGenerator/blob/263053adb7a300b62dcd74ed52d904a387918423/src/main/kotlin/com/robohorse/robopojogenerator/generator/consts/templates/ClassTemplate.kt#L19

Kotlin compiler generates a huge amount of garbage for [data classes](https://kotlinlang.org/docs/data-classes.html).

It's very easy to add a modifier, and very hard to analyze whether instances are used, for example, as a key in a HashMap (data classes implement `hashCode()`).

It's better to generate 'normal' classes and let the user decide on their own whether to make their classes `data`.

**Comment by robohorse** [comment]
Hey, thanks for the feedback. Please check 2.3.8 - it will be live soon.
