### ISSUE TITLE
Key "A" convert to "private String A", but not to "private String a"

### ISSUE THREAD

**Issue by ShyshkinOleksii** [robohorse/RoboPOJOGenerator#119]
Convert JSON to Java Jackson: 
key with > 1char convert to first letter with lowerCase (OK)
key with = 1char convert to first (and only one) letter with UpperCase (notOK)

-----------
Input JSON to POJOgenerator: 
{
	"Subject": {
		"A": "some1",
		"B": "some2",
		"CLONGNAME": "some3"
	}
}
-----------
result: 
public class Subject{

    @JsonProperty("A")
    private String A;

    @JsonProperty("B")
    private String B;

    @JsonProperty("CLONGNAME")
    private String cLONGNAME;
}

**Comment by robohorse** [comment]
Hey, thanks for the report. Please check 2.3.8 - it will be live soon.
