### ISSUE TITLE
[FEATURE] Add option to support annotation such as @JsonClass for Moshi

### ISSUE THREAD

**Issue by forceporquillo** [robohorse/RoboPOJOGenerator#129]
First of all, I would like to thank you for providing this kind of plugin where it helps and improves every developer's productivity. Also, it would be very cool if there's an option or settings that we can add prior to creating the POJO template.

For example in the `Moshi` model.
```
@JsonClass(generateAdapter = true)
data class ProductResponse(
    @Json(name="quantity")
    val quantity: Int? = null,

    @Json(name="addedBy")
    val addedBy: String? = null,

   ...
)
```
We can optionally add an annotation class such as `@JsonClass(generateAdapter=true)` for the model type.

Thanks!

**Comment by robohorse** [comment]
Hey @forceporquillo, thanks for the really nice feedback! Please check 2.3.8 - it will be live soon
