### ISSUE TITLE
IntelliJ 2022.x is only supported by older version of the plugin

### ISSUE THREAD

**Issue by PorkLip** [robohorse/RoboPOJOGenerator#130]
Using a recent release of IntelliJ ( 2022.x ) will install 2.3.3 of the plugins since 2.3.4 and 2.3.5 only supports older version of IntelliJ.

Does releases after 2.3.3 contain anything that prevents it from working on more recent versions of IntelliJ?

**Comment by robohorse** [comment]
Hi @PorkLip ! Thanks for this report. I've fixed it (release 2.3.6)
