### ISSUE TITLE
Support IntelliJ IDEA 2022.3

### ISSUE THREAD

**Issue by Elhussein-Hamed** [robohorse/RoboPOJOGenerator#136]
Could you please support IntelliJ IDEA 2022.3. The following error can be seen when using the plugin as a dependency with intellij version set to 2022.3

```Plugin 'com.robohorse.robopojogenerator:2.3.8' is not compatible to: IC-223.7571.182```

build.gradle.kts:
``` 
intellij {
    version.set("2022.3")
    type.set("IC") // Target IDE Platform

    plugins.set(listOf("com.robohorse.robopojogenerator:2.3.8"))
}
```

Thanks.

**Comment by robohorse** [comment]
Hi @Elhussein-Hamed !
Thanks for contributing and sorry for the delay. The last version 2.3.9 is live now.

**Comment by Elhussein-Hamed** [comment]
Thanks for the update!
