### ISSUE TITLE
Add support for Kotlinx Serialization

### ISSUE THREAD

**Issue by moallemi** [robohorse/RoboPOJOGenerator#145]
Hello @robohorse,

I hope all is well with you! You might remember me from our collaboration on the Eva and A1 projects.

I've been working with your library and find it quite useful. One enhancement I've been considering is the integration of kotlinx serialization to improve the serialization capabilities of the library.

Would you be open to such a contribution? I'd be more than happy to work on this feature and submit a pull request for your review.

Looking forward to hearing your thoughts.

Best regards,

**Comment by robohorse** [comment]
hey @moallemi , It is live now 🎉 
Please check the release 2.6.0

**Comment by moallemi** [comment]
Hey, Thanks for the update and new release 🙏👌
