### ISSUE TITLE
Incorrect compatibility range

### ISSUE THREAD

**Issue by jorissaenen** [robohorse/RoboPOJOGenerator#148]
I'm currently running Intellij 2024.1 (stable version) and the latest compatible version of the plugin is 2.3.3 regarding JetBrains: https://plugins.jetbrains.com/plugin/8634-robopojogenerator/versions. Manual installation won't work eighter.

**Comment by robohorse** [comment]
Hey @jorissaenen , thanks a lot for the report. Please check the latest version 2.5.0
