### ISSUE TITLE
Incompatible with idea2024.2

### ISSUE THREAD

**Issue by jianguyuxing** [robohorse/RoboPOJOGenerator#151]
com.intellij.diagnostic.PluginException: Cannot create class com.robohorse.robopojogenerator.action.GeneratePOJOAction (classloader=PluginClassLoader(plugin=PluginDescriptor(name=RoboPOJOGenerator, id=com.robohorse.robopojogenerator, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2024.2\plugins\RoboPOJOGenerator, version=2.3.3, package=null, isBundled=false), packagePrefix=null, state=active, parents=PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=G:\ideaIU-2024.1.win\lib, version=242.20224.387, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.log.impl, descriptorPath=intellij.platform.vcs.log.impl.xml, path=G:\ideaIU-2024.1.win\lib, version=242.20224.387, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.dvcs.impl, descriptorPath=intellij.platform.vcs.dvcs.impl.xml, path=G:\ideaIU-2024.1.win\lib, version=242.20224.387, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.collaborationTools, descriptorPath=intellij.platform.collaborationTools.xml, path=G:\ideaIU-2024.1.win\lib, version=242.20224.387, package=null, isBundled=true), ))

**Comment by robohorse** [comment]
hey @jianguyuxing , thanks a lot for the report. Please check the latest version 2.5.0
