### ISSUE TITLE
Maybe with AutoValue?

### ISSUE THREAD

**Issue by lopspower** [robohorse/RoboPOJOGenerator#22]
Shame that it doesn't generate the class with AutoValue format..

- Google Auto -> [https://github.com/google/auto](https://github.com/google/auto)
- Google AutoValue -> [https://github.com/google/auto/tree/master/value](https://github.com/google/auto/tree/master/value)

Example AutoValue Class:
```
@AutoValue
public abstract class Example {

    @SerializedName("id")
    public abstract int getId();

    @SerializedName("name")
    public abstract String getName();

    public static TypeAdapter<Example> typeAdapter(Gson gson) {
        return new AutoValue_Example.GsonTypeAdapter(gson);
    }
}
```

**Comment by robohorse** [comment]
hmm... ok, maybe will coming soon)

**Comment by robohorse** [comment]
done. Will be in release 1.6

**Comment by lopspower** [comment]
Good job, thank you :)
