### ISSUE TITLE
not predefined jsonarray   

### ISSUE THREAD

**Issue by pranavlathigara** [robohorse/RoboPOJOGenerator#27]
I have json array with not specific number of n-level array... 

1st Object --  Array A [Array A [Array A [Array A ]]]
12nd Object --  Array A [Array A [Array A ]]

i am using GSOn for Parsing so how can i make pojo

**Comment by robohorse** [comment]
ok, thanks for this issue, i will fix it. 
But now, you can wrap your JSONArray for POJO generation like following: {"data":[ ]} and then remove useless root dto object ("Response.java")

**Comment by pranavlathigara** [comment]
my json is `"CategoryDetails":{
  "CategoryID": 1,
  "CategoryName": "Sandwich",
  "ImgPath": "1",
  "SubCategoryDetail": [
    
  ],
  
},
{
  "CategoryID": 2,
  "CategoryName": "Drink",
  "ImgPath": "Location",
  "SubCategoryDetail": [
    {
      "CategoryID": 7,
      "CategoryName": "Tea & Coffee",
      "ImgPath": "1",
      "SubCategoryDetail": [
        {
          "CategoryID": 9,
          "CategoryName": "Tea",
          "ImgPath": "S",
          "SubCategoryDetail": [
            
          ],
          
        }
      ],
      
    },
    {
      "CategoryID": 10,
      "CategoryName": "Beer",
      "ImgPath": "z",
      "SubCategoryDetail": [
        
      ],
      
    }
  ],
  
},
{
  "CategoryID": 8,
  "CategoryName": "WATER",
  "ImgPath": "S",
  "SubCategoryDetail": [
    
  ],
  
}
],
`

**Comment by robohorse** [comment]
hmm.. can you validate your JSON structure and publish it here?
Plugin supports multiple inner arrays. There is no problems with this JSON
```json
{
  "data": [
    {
      "array": [
        {
          "some_value": "text",
          "another_array": [
            {
              "available": true
            }
          ]
        }
      ]
    }
  ],
  "int_value": 2
}
```

**Comment by pranavlathigara** [comment]
`{
  "CategoryDetails": [
    {
      "CategoryID": 1,
      "CategoryName": "Sandwich",
      "ImgPath": "1",
      "DiscountDetail": [
        
      ],
      "SubCategoryDetail": [
        
      ],
      "CategoryWiseProduct": [
        {
          "DiscountDetail": [
            
          ],
          "ProductID": 5,
          "CategoryID": 1,
         
          "TimeSheetWiseProduct": [
            
          ],
          "ComboDetail": [
            
          ]
        }
      ],
      "TaxGroupDetail": [
        
      ]
    },
    {
      "CategoryID": 2,
      "CategoryName": "Drink",
      "ImgPath": "Location",
      "DiscountDetail": [
        
      ],
      "SubCategoryDetail": [
        {
          "CategoryID": 7,
          "CategoryName": "Tea & Coffee",
          "ImgPath": "1",
          "DiscountDetail": [
            
          ],
          "SubCategoryDetail": [
            {
              "CategoryID": 9,
              "CategoryName": "Tea",
              "ImgPath": "S",
              "DiscountDetail": [
                
              ],
              "SubCategoryDetail": [
                
              ],
              "CategoryWiseProduct": [
                {
                  "DiscountDetail": [
                    
                  ],
                  "ProductID": 3,
                  "CategoryID": 9,
                  "ProductName": "Black Tea",
                
                  "TimeSheetWiseProduct": [
                    {
                      "FromTime": "07:15:34.1670000",
                      "ToTime": "11:15:34.1670000",
                      "StartDate": "8/22/2016 12:00:00 AM",
                      "EndDate": "8/22/2017 12:00:00 AM",
                      "Day": 1
                    }
                  ],
                  "ComboDetail": [
                    
                  ]
                }
              ],
              "TaxGroupDetail": [
                
              ]
            }
          ],
          "CategoryWiseProduct": [
            {
              "DiscountDetail": [
                
              ],
              "ProductID": 143,
              "CategoryID": 7,
            
              "TimeSheetWiseProduct": [
                
              ],
              "ComboDetail": [
                
              ]
            }
          ],
          "TaxGroupDetail": [
            
          ]
        },
        {
          "CategoryID": 10,
          "CategoryName": "Beer",
          "ImgPath": "z",
          "DiscountDetail": [
            
          ],
          "SubCategoryDetail": [
            
          ],
          "CategoryWiseProduct": [
            {
              "DiscountDetail": [
                
              ],
              "ProductID": 4,
              "CategoryID": 10,
          
              "TimeSheetWiseProduct": [
                
              ],
              "ComboDetail": [
                
              ]
            }
          ],
          "TaxGroupDetail": [
            
          ]
        }
      ],
      "CategoryWiseProduct": [
        {
          "DiscountDetail": [
            
          ],
          "ProductID": 1,
          "CategoryID": 2,
      
          "TimeSheetWiseProduct": [
            
          ],
          "ComboDetail": [
            {
              "ComboSetID": 1,
              "ComboSetName": "Drink Combo",
              "CategoryID": 2,
              "CProductID": 1,
              "ComboProductDetail": [
                {
                  "ProductID": 2,
                  "IsDefault": true,
                  "ProductName": "Thump-Up"
                }
              ]
            }
          ]
        },
        {
          "DiscountDetail": [
            
          ],
          "ProductID": 2,
          "CategoryID": 2,
        
          "TimeSheetWiseProduct": [
            
          ],
          "ComboDetail": [
            
          ]
        },
        {
          "DiscountDetail": [
            
          ],
          "ProductID": 142,
          "CategoryID": 2,
        
          "TimeSheetWiseProduct": [
            
          ],
          "ComboDetail": [
            
          ]
        }
      ],
      "TaxGroupDetail": [
        
      ]
    },
    {
      "CategoryID": 8,
      "CategoryName": "WATER",
      "ImgPath": "S",
      "DiscountDetail": [
        
      ],
      "SubCategoryDetail": [
        
      ],
      "CategoryWiseProduct": [
        
      ],
      "TaxGroupDetail": [
        
      ]
    }
  ]
}`

**Comment by robohorse** [comment]
i converted your json with following result:
Root object:
```java
	@SerializedName("CategoryDetails")
	@Expose
	private List<CategoryDetailsItem> CategoryDetails;
```
CategoryDetailsItem:

```java
	@SerializedName("CategoryID")
	@Expose
	private int CategoryID;
	@SerializedName("ImgPath")
	@Expose
	private String ImgPath;
	@SerializedName("TaxGroupDetail")
	@Expose
	private List<Object> TaxGroupDetail;
	@SerializedName("DiscountDetail")
	@Expose
	private List<Object> DiscountDetail;
	@SerializedName("CategoryWiseProduct")
	@Expose
	private List<CategoryWiseProductItem> CategoryWiseProduct;
	@SerializedName("CategoryName")
	@Expose
	private String CategoryName;
	@SerializedName("SubCategoryDetail")
	@Expose
	private List<Object> SubCategoryDetail;

```

CategoryWiseProductItem:
```java
	@SerializedName("CategoryID")
	@Expose
	private int CategoryID;
	@SerializedName("ComboDetail")
	@Expose
	private List<Object> ComboDetail;
	@SerializedName("DiscountDetail")
	@Expose
	private List<Object> DiscountDetail;
	@SerializedName("TimeSheetWiseProduct")
	@Expose
	private List<Object> TimeSheetWiseProduct;
	@SerializedName("ProductID")
	@Expose
	private int ProductID;

```
and accessors for that fields.

I can see only one problem: fields not starts with lower case.
If you talk about List<Object>, you should to see, that your JSON has no data for that objects
```json
"TaxGroupDetail": [

  ]
```
and that is reason to create fields like list of objects. You can fill your tax group details and plugin will create TaxGroupDetail.java with it own fields.

**Comment by pranavlathigara** [comment]
i am confuse about SubCategoryDetail has one more SubCategoryDetail or may be not it is  variable 

SubCategoryDetail-->SubCategoryDetail-->SubCategoryDetail ---> N level (Variable number of)

**Comment by robohorse** [comment]
O_o i see)
You shout to fill all SubCategoryDetail for generation - nice bug. Ill try to fix it later (maybe today)
Thanks!

**Comment by robohorse** [comment]
hmm
this [site](http://www.jsonschema2pojo.org/) also cant parse your json correct :)
Please create dto object directly for SubCategoryDetail item. I will see this bug today

**Comment by robohorse** [comment]
done in 1.8 - will be after review (2 business days)
