### ISSUE TITLE
Do you like Kotlin support?

### ISSUE THREAD

**Issue by wafer-li** [robohorse/RoboPOJOGenerator#33]
I implement the Kotlin support in my own fork which can generate the [Kotlin Data Class](https://kotlinlang.org/docs/reference/data-classes.html)

I also notice that, the generated field didn't use the camelCase, so I fix it in my fork.

But there are a lot of commits, so I raise this issue to question about it.

If you like it, I will then raise the PR, or you could close this issue.

**Comment by robohorse** [comment]
Yes, that is great idea!

I reworked class processing by adding PostProcessorsFactory and now it is easy to add your feature. If you want, you can create PR and i will add you to vendors list (if you want it), but please do your feature like AutoValue (now in master) before. Sorry, if it will required some reworks of your code, but it is better way:)

**Comment by wafer-li** [comment]
OK,  I will check out the master and start to migrate.

It might take some time because I have no idea what is AutoValue.

**Comment by robohorse** [comment]
> It might take some time because I have no idea what is AutoValue.

dont care about it. It is just example for you:)
Create post processor like [this](https://github.com/robohorse/RoboPOJOGenerator/blob/master/src/main/java/com/robohorse/robopojogenerator/generator/postprocessors/AutoValueClassPostProcessor.java)

and generate kotlin file throw [factory](https://github.com/robohorse/RoboPOJOGenerator/blob/master/src/main/java/com/robohorse/robopojogenerator/generator/PostProcessorFactory.java)

**Comment by wafer-li** [comment]
OK, I see.

**Comment by wafer-li** [comment]
The job is almost done.

You could ckeck my schedule at https://github.com/wafer-li/RoboPOJOGenerator/issues if you like.

I will probably create PR tomorrow, or at 2016-10-24T13:00:00+09:00, which is more precise.

**Comment by robohorse** [comment]
That is GREAT! 
New version will be released next evening after merge :)

**Comment by robohorse** [comment]
Also create jetBrains [account](https://account.jetbrains.com/login) (if you dont have it) and say it to me - i will add you to the authors list

**Comment by robohorse** [comment]
Cool! I will see it today

**Comment by robohorse** [comment]
Look [here](https://github.com/robohorse/RoboPOJOGenerator#people-who-help) :) I added info about your help. Thanks) Will be released soon

**Comment by wafer-li** [comment]
😄 Thank you so much for adding me to the contributors.

**Comment by robohorse** [comment]
i promised to add you to the vendors list, but i tested it on the test account and i seen that will give you administrator privileges. I cant do it, because i don't know you, and it can be dangerous to give that privileges for the stranger.)) I am really sorry

**Comment by wafer-li** [comment]
Don't mind.

:blush: It is my pleasure to contribute to such great product.

**Comment by robohorse** [comment]
was released now :)
