### ISSUE TITLE
Proceed type not so robust

### ISSUE THREAD

**Issue by wafer-li** [robohorse/RoboPOJOGenerator#37]
Try this JSON:

```
{
	"!!@##$%^$3351$%^&23^1_--=---___-_-yte": "test robust",
    "private": "Java preserve field",
    "_test": "Kotlin preserve field"
}
```

Actually, Kotlin don't allow the `_`, `__`, `___` and so on to be the first char.

**Comment by robohorse** [comment]
lol, you have a crazy back-end team)))

**Comment by wafer-li** [comment]
You know, the back-end team which is made of undergraduate students.

**Comment by robohorse** [comment]
done. will be in release 1.7
