### ISSUE TITLE
Improve generated code style when annotated

### ISSUE THREAD

**Issue by wafer-li** [robohorse/RoboPOJOGenerator#39]
What about adding a extra empty line under the field when it is annotated?

Old:
![image](https://cloud.githubusercontent.com/assets/12459199/19690160/b07090ac-9b0a-11e6-9116-67a47d8e1e7f.png)

New:
![](https://cloud.githubusercontent.com/assets/12459199/19689931/f6640f18-9b09-11e6-858b-884d3f420953.png)

I think the second looks better.
Especially in Kotlin:

![](https://cloud.githubusercontent.com/assets/12459199/19689803/8559f210-9b09-11e6-93be-9607fa65edc8.png)

![](https://cloud.githubusercontent.com/assets/12459199/19689965/10a09cf2-9b0a-11e6-9a56-a4bde9c1e1e2.png)

**Comment by wafer-li** [comment]
Opps, sorry to make a redundant issue.

If you like, I will create the PR

**Comment by robohorse** [comment]
hm, if you think, that it will be more readable - why not?:)

**Comment by wafer-li** [comment]
@robohorse 

Because I am not sure if you like it, and this is your repo.
It is better to respect to your opinion, I think.
