### ISSUE TITLE
Generates only one class of the same name

### ISSUE THREAD

**Issue by EGecius** [robohorse/RoboPOJOGenerator#47]
In my json structure i have I have three objects names 'links'. Each one contain different objects. Unfortunately, this generators generates only one Links class, ignoring the others.

Other than that, the tool looks great :) would love to use it regularly.

**Comment by robohorse** [comment]
ok, thanks - i will fix it soon

**Comment by robohorse** [comment]
Sorry, but will not fixed for some reasons:
1) JSON keys in one object must be unique
2) JSON keys in all inner object should be unique - we can use not unique keys technically, but if it will be supported, recursive objects will be never supported, like following:
`
{
  "widget": {
    "value": 2,
    "widget": {
      "value": 2,
      "widget": {
        ....
      }
    }
  }
}
`
