### ISSUE TITLE
Incorrect Signature

### ISSUE THREAD

**Issue by anuinsonix** [robohorse/RoboPOJOGenerator#59]
Hi

I am getting error pop up with Incorrect Signature message over it.I have validated my JSON response from JSON Lint as well.Please let me know,Where I am doing wrong.

Thanks

**Comment by robohorse** [comment]
hmm.... can you add example of your JSONObject here?

**Comment by anuinsonix** [comment]
Hello

Greetings of the day!!!

Sure,PFA


Thanks and Regards
Anu

**Comment by robohorse** [comment]
cant reproduce
