### ISSUE TITLE
Move "Generate POJO from JSON" down on the list

### ISSUE THREAD

**Issue by woj-tek** [robohorse/RoboPOJOGenerator#64]
This is a tiny visual improvement, but currently "Generate POJO from JSON" resides on the top of the list so if we want to create new class (which most of the time happens often than generating class from JSON) I'm forced to either type or change selection.

It would be great if the option "Generate POJO from JSON" could be moved down on the list.

**Comment by robohorse** [comment]
ok, i agree)
