### ISSUE TITLE
Order of the generated properties in data files

### ISSUE THREAD

**Issue by MikeShysh** [robohorse/RoboPOJOGenerator#67]
Hello,

Intellijidea 1.8.5 plugin, kotlin, jackson

I faced a strange behaviour when the order of keys is different.
For ``` {"login":"test","password":"pass"}``` the generated class is
```
data class AuthInfoCredentials(
	@field:JsonProperty("password")
	val password: String? = null

	@field:JsonProperty("login")
	val login: String? = null,
)
```
And you should explicitly assign properties in order not to be messed up (AuthInfoCredentials(login = data[Config.user],password = data[Config.password])).

Is it possible to generate data classes with properties order the same as they occur in json?

**Comment by robohorse** [comment]
In JSON, an object is defined thus:
```
An object is an unordered set of name/value pairs.
```
See [this](http://json.org)

**Comment by MikeShysh** [comment]
Its not about json, its about usability of auto generator. I need to exactly know how the final data class looks like

**Comment by robohorse** [comment]
@MikeShysh [here](https://github.com/robohorse/RoboPOJOGenerator/blob/master/src/main/java/com/robohorse/robopojogenerator/generator/RoboPOJOGenerator.java) is the major problem (line 28). I dont want to write my own parser. If you know other ways plz tell me
