### ISSUE TITLE
Don't replace names of the json

### ISSUE THREAD

**Issue by benju69** [robohorse/RoboPOJOGenerator#68]
Hi, 

Cool plugin but I have a problem with it, the generator don't keep the underscore in the names.
For example "record_timestamp" become "recordTimestamp"

Also add on option to not init fields at null for Kotlin 
(val recordTimestamp: String? = nul,l => val record_timestamp: String,)

**Comment by mwshubham** [comment]
+ what about adding the default constructor as well to initialize default.

**Comment by robohorse** [comment]
That is normal for plain POJO. Because your source JSON file can have incompatible file names with current language (Java/Kotlin). Better way is to use generation for some frameworks like GSON, Jackson.. etc -> real names will be keep by annotation.
