### ISSUE TITLE
Can't find @Generated annotation package

### ISSUE THREAD

**Issue by serjooo** [robohorse/RoboPOJOGenerator#74]
First time I use The RoboPOJOGenerator not sure if its because of updating to Android Studio 3.0 or not, or if its from my setup.

**Comment by robohorse** [comment]
just javax.annotation.Generated;

You can get it [here](https://mvnrepository.com/artifact/javax.annotation/javax.annotation-api/1.3.1), or [here](https://mvnrepository.com/artifact/javax.annotation/jsr250-api/1.0)

**Comment by serjooo** [comment]
Thank you for the reference and the great project really appreciate it!

**Comment by anburocky3** [comment]
What is the use of `@Generated("com.robohorse.robopojogenerator")` annotation?
