### ISSUE TITLE
Creating a lot of JSONMembers even though they are all the same.

### ISSUE THREAD

**Issue by pesjak** [robohorse/RoboPOJOGenerator#75]
I have a long JSON request, and it creates some classes like it has to:
[Click here](http://prntscr.com/hda0mx)
But others are all:
[Doesn't work](http://prntscr.com/hda066)
[Too many classes](http://prntscr.com/hda0b8)

**Comment by robohorse** [comment]
Look [this](https://github.com/robohorse/RoboPOJOGenerator/issues/74) to get "Generated" dependency.
>Too many classes
You have crazy back-end team). Do you have your opinion about fix it?

**Comment by pesjak** [comment]
Probably will have to go by hand and check every single one which is a duplicate. There are around 20k lines of JSON, so yeah. 1 huge file with code_registers that is needed. So yeah this is the only option. Unless you have a better idea :)

**Comment by robohorse** [comment]
hmm
>Probably will have to go by hand and check every single one which is a duplicate

Do that members have similar structure, but different key names?

**Comment by pesjak** [comment]
Yes they have similar but key names are the same it is ID.
Example:
 "suitability":{
         "id":"62",
         "text":"suitability",
         "option":[
            {
               "id":"220",
               "text":"Somebody",
               "option":false
            },
            

So option means does it have an array or not. If yes then the arrey is the object otherwise it is false. Meaning that is the end object.

**Comment by robohorse** [comment]
ok, i will try to understand it just a little later)

**Comment by pesjak** [comment]
Thank you ^^, but you don't need to do that I'm sure you have your hands full with other stuff. I'll have to figure this out on my own. So thanks for the help 👍
