### ISSUE TITLE
JSON Schema to POJO issue

### ISSUE THREAD

**Issue by ultraon** [robohorse/RoboPOJOGenerator#77]
Hello, I've tried this plugin with Android Studio, and the generating POJO from JSON schema doesn't work as described in [this article](https://android.jlelse.eu/android-studio-tip-8-json-models-13ce45e4e8f3). Any suggestions?

**Comment by robohorse** [comment]
hi, hmm... i see that article first time) ok, i will think about schema support

**Comment by bilak** [comment]
@robohorse hi, I'm interested also in POJO from JSON schema. Do you have any plan for this?

**Comment by robohorse** [comment]
@bilak hey, thanks for reminder. Yes, I guess it is possible to implement it soon.

**Comment by robohorse** [comment]
Sorry a bit out of time - I closed this one. But please feel free to contribute to this project.

**Comment by robohorse** [comment]
But in general it sounds like a great idea! @ultraon , @bilak please feel free to contribute to this project: i migrated it into kotlin 2.0 and would be happy to release those features 😉
