### ISSUE TITLE
Parcelable option?

### ISSUE THREAD

**Issue by wbinarytree** [robohorse/RoboPOJOGenerator#79]
Thanks for this great plugin. 
Kotlin has a good tool that generator parcelable in Android with just annotation like this 

```kotlin
@Parcelize
data class User(val firstName: String, val lastName: String) : Parcelable
```

it would be nice that in this plugin can add this annotation with this pojo that generated. 

Thanks!

**Comment by robohorse** [comment]
Hey) This feature is available now in version 2.1.0.
