### ISSUE TITLE
not working in android studio 3.1

### ISSUE THREAD

**Issue by riddhee** [robohorse/RoboPOJOGenerator#81]

**Comment by robohorse** [comment]
can you provide more info plz? My environment:
Android Studio 3.1
Build #AI-173.4670197, built on March 22, 2018
JRE: 1.8.0_152-release-1024-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.3

all works fine)

**Comment by robohorse** [comment]
>it is not clickable using mouse 
it happens while indexing processing

>it will generate
only class when response starts from array

hmm, so strange issue, but it happens. Ok, thanks - i will fix it.

**Comment by riddhee** [comment]
hello

**Comment by riddhee** [comment]
*it happens while indexing processing*
no indexing is already completed when project is load still it is not
clickable

**Comment by robohorse** [comment]
Android Studio 3.1.2
Build #AI-173.4720617, built on April 14, 2018
JRE: 1.8.0_152-release-1024-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.4

still can't reproduce :(
