### ISSUE TITLE
primitive wrapper class is better

### ISSUE THREAD

**Issue by slankka** [robohorse/RoboPOJOGenerator#84]
While writing API in MVC controllers, the primitive types in parameters cannot represent `none`, they are always default to 0, and the value 0 stands for only `zero`，however, wrapper class can differ in `zero` or `none`. 

On my suggestion, it will be better if we have "Using Primitive Wrapper Class" option.

**Comment by robohorse** [comment]
Hey) So, if I understand correctly, you want to use Boxed java types instead of primitive types? I think that is possible. I will add checkbox for it soon.

**Comment by robohorse** [comment]
Done (build 2.2.0)
