### ISSUE TITLE
android studio 3.6.1 not seeing the generate option

### ISSUE THREAD

**Issue by Lynpo** [robohorse/RoboPOJOGenerator#86]
Tried install/uninstall, enable/disable RoboPOJOGeneragor in android studio plugin many times, still not seeing the 'Generate POJO from JSON' option in [NEW] menu

**Comment by Karwani** [comment]
I got the same problem, have you found a solution?

**Comment by robohorse** [comment]
I found the problem, sorry guys - my mistake. Could you please check new build 1.9.3?

**Comment by Lynpo** [comment]
> I found the problem, sorry guys - my mistake. Could you please check new build 1.9.3?

thanks, it fixed.
